# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 10
  - name: Highlights
    url: post
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Vision
    url: vision
    weight: 40
  - name: Research
    url: research
    weight: 50
  - name: Publications
    url: publication
    weight: 60
  - name: Opportunities
    url: openning
    weight: 70
  - name: Contact
    url: contact
    weight: 80
